name: "cache-command-action"
description: ""

inputs:
  file:
    description: 'A file to cache and restore command output'
    required: false
    default: '.cacheCommandOutput'
  run:
    description: 'A command that will get the output and use it as a key'
    required: true

outputs:
  hit:
    description: 'A boolean value to indicate an exact match was found for the key'
  output:
    description: 'Output of the command'

runs:
  using: "node16"
  main: "index.js"
