name: Test

on:
  push:
    branches: [main]
    paths-ignore:
      - '.github/workflows/cache.yml'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ./
        id: cache
        with:
          run: sh -c "echo '{\"foo\": 0}' | jq ."
      - name: Get outputs
        if: always()
        run: |
          ls -a /home/runner/work/cache-command-action/cache-command-action
          echo "output: ${{ steps.cache.outputs.output }}"
          echo "hit: ${{ steps.cache.outputs.hit }}"
