name: Test

on:
  push:
    branches: [main]
    paths-ignore:
      - '.github/workflows/cache.yml'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: pnpm run
        run: |
          pnpm run build
          pnpm run lint

      - uses: ./
        id: cache
        with:
          run: pnpm -v

      - name: Get outputs
        if: always()
        run: |
          echo "output: ${{ steps.cache.outputs.output }}"
          echo "hit: ${{ steps.cache.outputs.hit }}"
