name: Test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: npm i @actions/cache
      - uses: ./
        id: cache
        with:
          file: ''
          run: ''
      - name: Get outputs
        run: |
          echo "output: ${{ steps.cache.outputs.output }}"
          echo "hit: ${{ steps.cache.outputs.hit }}"
